#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

./js-renamer.sh genosrtc.min.js 'F0' 'createArray'
./js-renamer.sh genosrtc.min.js '$8' 'generateRandomId'
./js-renamer.sh genosrtc.min.js 'N0' 'generatedPeerId'
./js-renamer.sh genosrtc.min.js 'V0' 'promiseAll'
./js-renamer.sh genosrtc.min.js 't$' 'isBrowserEnv'
./js-renamer.sh genosrtc.min.js 'e$' 'objectEntries'
./js-renamer.sh genosrtc.min.js 'R8' 'objectFromEntries'
./js-renamer.sh genosrtc.min.js 'J1' 'objectKeys'
./js-renamer.sh genosrtc.min.js '$Q' 'noop'
./js-renamer.sh genosrtc.min.js 'J0' 'createGenosError'
./js-renamer.sh genosrtc.min.js 'Q8' 'buildNamespacedKey'
./js-renamer.sh genosrtc.min.js 'QQ' 'shuffleWithSeed'
./js-renamer.sh genosrtc.min.js 'sQ' 'ICE_GATHERING_TIMEOUT_MS'
./js-renamer.sh genosrtc.min.js 'JQ' 'ICE_GATHERING_EVENT'
./js-renamer.sh genosrtc.min.js 'qQ' 'SDP_OFFER'
./js-renamer.sh genosrtc.min.js 'tQ' 'SDP_ANSWER'
./js-renamer.sh genosrtc.min.js 'eQ' 'DEFAULT_STUN_SERVER_CONFIGS'
./js-renamer.sh genosrtc.min.js 'L8' 'createPeerConnection'
./js-renamer.sh genosrtc.min.js '$J' 'uint8ArrayPrototype'
./js-renamer.sh genosrtc.min.js 'w8' 'MESSAGE_TYPE_MAX_BYTES'
./js-renamer.sh genosrtc.min.js 'GQ' 'TYPE_HEADER_OFFSET'
./js-renamer.sh genosrtc.min.js 'I8' 'NONCE_HEADER_OFFSET'
./js-renamer.sh genosrtc.min.js 'k8' 'FLAGS_HEADER_OFFSET'
./js-renamer.sh genosrtc.min.js 'q8' 'PROGRESS_HEADER_OFFSET'
./js-renamer.sh genosrtc.min.js 'G8' 'PAYLOAD_HEADER_OFFSET'
./js-renamer.sh genosrtc.min.js 'J8' 'MAX_CHUNK_SIZE'
./js-renamer.sh genosrtc.min.js 'A8' 'UINT8_MAX'
./js-renamer.sh genosrtc.min.js '$$' 'BUFFER_LOW_EVENT_NAME'
./js-renamer.sh genosrtc.min.js 'h0' 'namespacedChannel'
./js-renamer.sh genosrtc.min.js 'Q$' 'MAX_MESSAGE_CHUNKS'
./js-renamer.sh genosrtc.min.js 'QJ' 'BUFFER_RETRY_LIMIT'
./js-renamer.sh genosrtc.min.js 'JJ' 'BUFFER_RETRY_DELAY_MS'
./js-renamer.sh genosrtc.min.js 'zQ' 'createPeerMesh'
./js-renamer.sh genosrtc.min.js 'qJ' 'MAX_OFFER_PEERS'
./js-renamer.sh genosrtc.min.js 'GJ' 'ANNOUNCE_INTERVAL_MS'
./js-renamer.sh genosrtc.min.js 'UQ' 'OFFER_EXPIRATION_MS'
./js-renamer.sh genosrtc.min.js 'jQ' 'createRelayOrchestrator'
./js-renamer.sh genosrtc.min.js 'YQ' 'RECONNECT_DELAY_MS'
./js-renamer.sh genosrtc.min.js 'S8' 'relayReconnectBackoff'
./js-renamer.sh genosrtc.min.js 'XQ' 'relaySocketCache'
./js-renamer.sh genosrtc.min.js 'ZQ' 'connectRelaySocket'
./js-renamer.sh genosrtc.min.js 'KQ' 'createSocketSnapshot'
./js-renamer.sh genosrtc.min.js 'MQ' 'selectRelays'
./js-renamer.sh genosrtc.min.js 'l0' 'activeRelaySockets'
./js-renamer.sh genosrtc.min.js 'zJ' 'DEFAULT_RELAY_REDUNDANCY'
./js-renamer.sh genosrtc.min.js 'VQ' 'EVENT_TAG_IDENTIFIER'
./js-renamer.sh genosrtc.min.js 'CQ' 'NOSTR_EVENT_TYPE'
./js-renamer.sh genosrtc.min.js 'UJ' 'POW_REQUIREMENT_PATTERN'
./js-renamer.sh genosrtc.min.js 'J$' 'blockedRelays'
./js-renamer.sh genosrtc.min.js 'TQ' 'schnorrPrivateKey'
./js-renamer.sh genosrtc.min.js 'jJ' 'schnorrPublicKeyHex'
./js-renamer.sh genosrtc.min.js 'q$' 'subscriptionRoomMap'
./js-renamer.sh genosrtc.min.js 'z8' 'subscriptionHandlers'
./js-renamer.sh genosrtc.min.js 'YJ' 'roomKindCache'
./js-renamer.sh genosrtc.min.js 'BQ' 'nowInSeconds'
./js-renamer.sh genosrtc.min.js 'xQ' 'deriveRoomKind'
./js-renamer.sh genosrtc.min.js 'P8' 'normalizeRelayUrl'
./js-renamer.sh genosrtc.min.js 'XJ' 'DEFAULT_RELAY_URLS'
./js-renamer.sh genosrtc.min.js 'ZJ' 'handleRelayPayload'
./js-renamer.sh genosrtc.min.js 'KJ' 'getRelaySocket'
./js-renamer.sh genosrtc.min.js 'DQ' 'createSignedRelayEvent'
./js-renamer.sh genosrtc.min.js 'WQ' 'buildSubscribeRequest'
./js-renamer.sh genosrtc.min.js 'NQ' 'buildCloseRequest'
./js-renamer.sh genosrtc.min.js 'MJ' 'joinRoom'
./js-renamer.sh genosrtc.min.js 'DJ' 'snapshotRelaySockets'
